# Generated by Django 3.0 on 2019-12-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
    ]
